# Generated by Django 6.0.7 on 2026-07-23 09:16

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_alter_room_room_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingrecording",
            name="video_file",
            field=models.FileField(
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to="recordings/",
            ),
        ),
    ]
